export {default as Menu} from './menu/Menu'
export {default as About} from './about/About'
export {default as Infocard } from './infocard/Infocard'
export {default as Research} from './research/Research'
export {default as Teaching} from './teaching/Teaching'